### AUTH TEST ############################################
POST http://localhost:5000/login
Content-Type: application/json

{
    "kode_pendaftaran" : "A2",
    "password" : "ali"
}

###
GET  http://localhost:5000/me

###
DELETE http://localhost:5000/logout


### HPT TEST ############################################
GET http://localhost:5000/get-hpt

###
GET http://localhost:5000/get-hptbyid?id=13

###
POST http://localhost:5000/add-hpt
Content-Type: application/json

{
    "kode_penyakit": "kode",
    "nama_penyakit": "namapenyakit",
    "detail_penyakit": "123",
    "sm_penyakit": "123"

}
###
POST http://localhost:5000/edit-hpt?id=17
Content-Type: application/json

{
    "kode_penyakit": "new",
    "nama_penyakit": "new",
    "detail_penyakit": "123",
    "sm_penyakit": "123"
}

###
POST http://localhost:5000/delete-hpt?id=17





### RULES TEST ############################################
GET http://localhost:5000/get-rls

###
GET http://localhost:5000/get-rlsbyid?id=1

### 200
GET http://localhost:5000/get-rlsbydata?penyakit_id=1&gejala_id=4
### 404
GET http://localhost:5000/get-rlsbydata?penyakit_id=1&gejala_id=46

###
POST http://localhost:5000/add-rls
Content-Type: application/json

{
    "kode_rule": "kode",
    "penyakit_id": "1",
    "gejala_id": "46",
    "mb": "0.10",
    "md": "0.09"
}

### edit
POST http://localhost:5000/edit-rls?id=74
Content-Type: application/json

{
    "kode_rule": "new",
    "penyakit_id": "20",
    "gejala_id": "2",
    "mb": "1",
    "md": ""
}

###
POST http://localhost:5000/delete-rls?id=67



### EVD TEST ############################################
GET http://localhost:5000/get-evd

###
GET http://localhost:5000/get-evdbyid?id=47

###
POST http://localhost:5000/delete-evd?id=90




### USER TEST ############################################
GET http://localhost:5000/get-user

###
GET http://localhost:5000/get-userbyid?id=2

###
GET http://localhost:5000/get-userbyfirstletter?letter=a

###
# GET http://localhost:5000/get-userbyuuid?uuid=6265f8c6-64a5-456f-9402-13901d815e72

###
# GET http://localhost:5000/get-userbykodereg?kode_reg=1

###
POST http://localhost:5000/add-user
Content-Type: application/json

{
    "kode_pendaftaran" : "admin",
    "nama_user" : "!admin",
    "password" : "admin",
    "confPassword" : "admin",
    "no_hp" : "adminadmin",
    "role" : "admin"
}

###
POST http://localhost:5000/edit-user?id=3
Content-Type: application/json

{
    "kode_pendaftaran" : "123",
    "name" : "user1",
    "password" : "user1",
    "confPassword" : "user1",
    "phone" : "0808088080",
    "role" : "user"
}

###
POST http://localhost:5000/delete-user?id=9
